'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';

const SCRIPT_URL='https://script.google.com/macros/s/AKfycbxCRF7NdxVTNplnXwUjR-PUgTAd0xnh7J5Qj5cDFtVc5YDNQ0tgM6bmOpCPGWLubLC3/exec';
const cidades=['Santos','São Vicente','Praia Grande','Guarujá','Cubatão','Peruíbe','Itanhaém','Mongaguá','Itariri','Outra cidade'];
const interesses=['Serviços','Entregas','Fretes','Comércios','Ainda quero conhecer'];
const Field=({label,children})=><div className="field"><label>{label}</label>{children}</div>;

export default function CadastroCliente(){
 const [f,setF]=useState({nome:'',whatsapp:'',email:'',cidade:'',cidadeOutro:'',bairro:'',interesses:[],comoConheceu:'',indicacao:'',aceite:false,marketing:false});
 const [status,setStatus]=useState('idle'); const [erro,setErro]=useState('');
 const set=(k,v)=>setF(x=>({...x,[k]:v})); const cidade=f.cidade==='Outra cidade'?f.cidadeOutro:f.cidade;
 const mask=v=>{const d=v.replace(/\D/g,'').slice(0,11);if(d.length>10)return d.replace(/^(\d{2})(\d{5})(\d{4})$/,'($1) $2-$3');if(d.length>6)return d.replace(/^(\d{2})(\d{4})(\d{0,4})$/,'($1) $2-$3');if(d.length>2)return d.replace(/^(\d{2})(\d+)/,'($1) $2');return d};
 const toggle=x=>setF(v=>({...v,interesses:v.interesses.includes(x)?v.interesses.filter(i=>i!==x):[...v.interesses,x]}));
 const opiniao=useMemo(()=>[`Bairro: ${f.bairro||'-'}`,`Interesses: ${f.interesses.join(', ')||'-'}`,`Como conheceu: ${f.comoConheceu||'-'}`,`Indicação: ${f.indicacao||'-'}`,`Aceita novidades: ${f.marketing?'sim':'não'}`].join(' | '),[f]);
 async function submit(e){e.preventDefault();setErro('');if(!f.nome||!f.whatsapp||!f.email||!cidade||!f.bairro||!f.interesses.length){setErro('Preencha os campos obrigatórios.');return}if(f.comoConheceu==='Indicação'&&!f.indicacao){setErro('Informe quem indicou você.');return}if(!f.aceite){setErro('É necessário aceitar os Termos de Uso e a Política de Privacidade.');return}setStatus('sending');const dados={origem:'Cadastro rápido',nome:f.nome,whatsapp:f.whatsapp,email:f.email,cidade,tipo:'Cliente',ocupacao:'',avaliacao:'',indicaria:f.indicacao,opiniao};try{await fetch(SCRIPT_URL,{method:'POST',mode:'no-cors',body:new URLSearchParams(dados)});setStatus('success');window.scrollTo({top:0,behavior:'smooth'})}catch{setStatus('idle');setErro('Não foi possível enviar agora. Tente novamente.')}}
 if(status==='success')return <Page><div className="success"><img src="/logo-prontoai.webp" alt="ProntoAí"/><div className="check">✓</div><h1>Cadastro realizado!</h1><p>Seja bem-vindo ao ProntoAí. Em breve você poderá encontrar serviços, entregas, fretes e muito mais em um só lugar.</p><Link href="/" className="cta">Conhecer o ProntoAí</Link></div></Page>;
 return <Page><div className="shell"><header><Link href="/"><img src="/logo-prontoai.webp" alt="ProntoAí"/></Link><b>Cadastro gratuito</b></header><section className="hero"><span>Clientes • Litoral Sul</span><h1>Entre para o <em>ProntoAí.</em></h1><p>Seu cadastro leva menos de um minuto.</p></section><form onSubmit={submit} className="card"><h2>1. Seus dados</h2><div className="grid"><Field label="Nome completo *"><input value={f.nome} onChange={e=>set('nome',e.target.value)}/></Field><Field label="WhatsApp *"><input value={f.whatsapp} onChange={e=>set('whatsapp',mask(e.target.value))} inputMode="tel"/></Field><Field label="E-mail *"><input type="email" value={f.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Cidade *"><select value={f.cidade} onChange={e=>set('cidade',e.target.value)}><option value="">Selecione</option>{cidades.map(x=><option key={x}>{x}</option>)}</select></Field>{f.cidade==='Outra cidade'&&<Field label="Digite sua cidade *"><input value={f.cidadeOutro} onChange={e=>set('cidadeOutro',e.target.value)}/></Field>}<Field label="Bairro *"><input value={f.bairro} onChange={e=>set('bairro',e.target.value)}/></Field></div><h2>2. O que você pretende usar?</h2><div className="checks">{interesses.map(x=><label key={x}><input type="checkbox" checked={f.interesses.includes(x)} onChange={()=>toggle(x)}/><span>{x}</span></label>)}</div><h2>3. Como conheceu o ProntoAí?</h2><Field label="Origem"><select value={f.comoConheceu} onChange={e=>set('comoConheceu',e.target.value)}><option value="">Selecione</option><option>WhatsApp</option><option>Indicação</option><option>Instagram</option><option>Comércio</option><option>Profissional</option><option>Outro</option></select></Field>{f.comoConheceu==='Indicação'&&<Field label="Quem indicou você? *"><input value={f.indicacao} onChange={e=>set('indicacao',e.target.value)}/></Field>}<label className="consent"><input type="checkbox" checked={f.aceite} onChange={e=>set('aceite',e.target.checked)}/>Li e concordo com os Termos de Uso e Política de Privacidade. *</label><label className="consent"><input type="checkbox" checked={f.marketing} onChange={e=>set('marketing',e.target.checked)}/>Aceito receber novidades do ProntoAí pelo WhatsApp.</label>{erro&&<div className="error">{erro}</div>}<button className="cta" disabled={status==='sending'}>{status==='sending'?'Cadastrando...':'Criar meu cadastro'}</button></form></div></Page>;
}
function Page({children}){return <main className="page">{children}<style jsx global>{`.page{min-height:100vh;background:linear-gradient(145deg,#06192d 0,#0a355d 35%,#f7f9fc 35%);padding:28px 0 70px;color:#0b1728;font-family:Inter,Arial,sans-serif}.shell,.success{width:min(840px,calc(100% - 28px));margin:auto}header{display:flex;justify-content:space-between;align-items:center;color:white;margin-bottom:42px}header img,.success img{height:62px}header b{color:#dfff78}.hero{color:#fff;margin-bottom:28px}.hero span{font-size:.75rem;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.hero h1{font-size:clamp(2.2rem,6vw,4rem);line-height:1;margin:14px 0}.hero em{font-style:normal;color:#a6e100}.hero p{color:rgba(255,255,255,.75)}.card,.success{background:white;padding:32px;border-radius:28px;box-shadow:0 25px 65px rgba(6,25,45,.15)}h2{font-size:1.25rem;margin:8px 0 18px}h2:not(:first-child){border-top:1px solid #e5edf4;padding-top:26px;margin-top:30px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.field{margin-bottom:14px}.field>label{display:block;font-size:.78rem;font-weight:800;color:#475569;margin-bottom:7px}.field input,.field select{width:100%;border:1px solid #dce6ef;background:#fbfdff;border-radius:14px;padding:14px}.checks{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.checks label{display:flex;gap:9px;align-items:center;border:1px solid #dce6ef;background:#fbfdff;padding:13px;border-radius:14px}.consent{display:flex;gap:9px;margin-top:12px;font-size:.86rem}.cta{width:100%;display:flex;justify-content:center;border:0;border-radius:999px;background:#a6e100;color:#173000;padding:16px 22px;font-weight:900;margin-top:20px;text-decoration:none}.error{margin-top:14px;background:#fff1f0;color:#b42318;padding:12px;border-radius:12px}.success{margin-top:10vh;text-align:center}.success img{margin:0 auto 24px}.check{width:76px;height:76px;border-radius:22px;background:#eef9d5;color:#5e8200;display:grid;place-items:center;font-size:2rem;font-weight:900;margin:0 auto 18px}.success p{color:#647084;margin:10px 0 18px;line-height:1.6}@media(max-width:700px){.page{background:linear-gradient(145deg,#06192d 0,#0a355d 23%,#f7f9fc 23%)}.grid,.checks{grid-template-columns:1fr}.card{padding:22px}header img{height:52px}}`}</style></main>}
